// Cross-platform embedded shader table for bgfx.
// Generated shader bytecode headers are produced by bgfx_compile_shaders() in CMakeLists.txt.
// At build time, shaderc compiles each .sc source to all backends supported on the
// build platform (Metal on macOS, DXBC on Windows, GLSL+ESSL+SPIRV everywhere).
// This header includes the generated bytecode and declares the lookup table used by
// bgfx::createEmbeddedShader() to pick the right variant at runtime.

#pragma once

#include <bgfx/embedded_shader.h>

// ── Fix DXBC mismatch on non-Windows ──
// bgfx declares BGFX_PLATFORM_SUPPORTS_DXBC=1 on Linux (D3D via translation layers),
// but bgfx_compile_shaders() only generates DXBC shaders on Windows.
// Suppress the macro on non-Windows to avoid referencing non-existent arrays.
#if BGFX_PLATFORM_SUPPORTS_DXBC && !BX_PLATFORM_WINDOWS
#   undef  BGFX_EMBEDDED_SHADER_DXBC
#   define BGFX_EMBEDDED_SHADER_DXBC(...)
#endif

// ── Generated shader bytecode includes ──
// Paths are relative to ${GENERATED_SHADER_DIR} added to include dirs by CMake.
// Each header defines a static const uint8_t array (e.g. vs_basic_mtl[]).

// GLSL (OpenGL) — all platforms
#include "glsl/vs_basic.sc.bin.h"
#include "glsl/fs_basic.sc.bin.h"
#include "glsl/vs_textured.sc.bin.h"
#include "glsl/fs_textured.sc.bin.h"
#include "glsl/vs_lightmapped.sc.bin.h"
#include "glsl/fs_lightmapped.sc.bin.h"
#include "glsl/vs_lightmapped_bicubic.sc.bin.h"
#include "glsl/fs_lightmapped_bicubic.sc.bin.h"
#include "glsl/vs_water.sc.bin.h"
#include "glsl/fs_water.sc.bin.h"

// ESSL (OpenGL ES) — all platforms
#include "essl/vs_basic.sc.bin.h"
#include "essl/fs_basic.sc.bin.h"
#include "essl/vs_textured.sc.bin.h"
#include "essl/fs_textured.sc.bin.h"
#include "essl/vs_lightmapped.sc.bin.h"
#include "essl/fs_lightmapped.sc.bin.h"
#include "essl/vs_lightmapped_bicubic.sc.bin.h"
#include "essl/fs_lightmapped_bicubic.sc.bin.h"
#include "essl/vs_water.sc.bin.h"
#include "essl/fs_water.sc.bin.h"

// SPIR-V (Vulkan) — all platforms
#include "spirv/vs_basic.sc.bin.h"
#include "spirv/fs_basic.sc.bin.h"
#include "spirv/vs_textured.sc.bin.h"
#include "spirv/fs_textured.sc.bin.h"
#include "spirv/vs_lightmapped.sc.bin.h"
#include "spirv/fs_lightmapped.sc.bin.h"
#include "spirv/vs_lightmapped_bicubic.sc.bin.h"
#include "spirv/fs_lightmapped_bicubic.sc.bin.h"
#include "spirv/vs_water.sc.bin.h"
#include "spirv/fs_water.sc.bin.h"

// Metal — macOS / iOS only
#if BGFX_PLATFORM_SUPPORTS_METAL
#include "metal/vs_basic.sc.bin.h"
#include "metal/fs_basic.sc.bin.h"
#include "metal/vs_textured.sc.bin.h"
#include "metal/fs_textured.sc.bin.h"
#include "metal/vs_lightmapped.sc.bin.h"
#include "metal/fs_lightmapped.sc.bin.h"
#include "metal/vs_lightmapped_bicubic.sc.bin.h"
#include "metal/fs_lightmapped_bicubic.sc.bin.h"
#include "metal/vs_water.sc.bin.h"
#include "metal/fs_water.sc.bin.h"
#endif

// DXBC (Direct3D 11/12) — Windows only
#if BGFX_PLATFORM_SUPPORTS_DXBC
#include "dx11/vs_basic.sc.bin.h"
#include "dx11/fs_basic.sc.bin.h"
#include "dx11/vs_textured.sc.bin.h"
#include "dx11/fs_textured.sc.bin.h"
#include "dx11/vs_lightmapped.sc.bin.h"
#include "dx11/fs_lightmapped.sc.bin.h"
#include "dx11/vs_lightmapped_bicubic.sc.bin.h"
#include "dx11/fs_lightmapped_bicubic.sc.bin.h"
#include "dx11/vs_water.sc.bin.h"
#include "dx11/fs_water.sc.bin.h"
#endif

// ── Embedded shader lookup table ──
// Used by bgfx::createEmbeddedShader() to find the right bytecode for the active renderer.

static const bgfx::EmbeddedShader s_embeddedShaders[] = {
    BGFX_EMBEDDED_SHADER(vs_basic),
    BGFX_EMBEDDED_SHADER(fs_basic),
    BGFX_EMBEDDED_SHADER(vs_textured),
    BGFX_EMBEDDED_SHADER(fs_textured),
    BGFX_EMBEDDED_SHADER(vs_lightmapped),
    BGFX_EMBEDDED_SHADER(fs_lightmapped),
    BGFX_EMBEDDED_SHADER(vs_lightmapped_bicubic),
    BGFX_EMBEDDED_SHADER(fs_lightmapped_bicubic),
    BGFX_EMBEDDED_SHADER(vs_water),
    BGFX_EMBEDDED_SHADER(fs_water),
    BGFX_EMBEDDED_SHADER_END()
};
