/******************************************************************************
 *
 *    This file is part of the darkness project
 *    Copyright (C) 2024-2026 darkness contributors
 *
 *    This program is free software; you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation; either version 2 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 *****************************************************************************/

#include "ProbeManager.h"

#include "AudioLog.h"
#include "ProbeFile.h"
#include "logger.h"

#include <algorithm>
#include <cctype>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <sys/stat.h>
#include <thread>
#include <vector>

#ifdef _WIN32
#include <direct.h>
#endif

#include <phonon.h>

namespace Darkness {

// ── Engine ↔ Steam Audio coordinate-system bridge ─────────────────────────
//
// Dark Engine uses a right-handed Z-up system: +X right, +Y forward, +Z up.
// Steam Audio uses a right-handed Y-up system: +X right, +Y up, -Z ahead.
//
// Mapping (matches AudioService.cpp boundary helpers):
//   engine +X (yaw=0 ahead) → IPL -Z (IPL ahead)
//   engine +Y (engine fwd)  → IPL -X (IPL left)
//   engine +Z (up)          → IPL +Y (up)
//
// In coordinate form: engine (x, y, z) → IPL (-y, z, -x).  Determinant
// of the rotation matrix is +1 (handedness preserved).
//
// Probe generation with UNIFORMFLOOR raycasts along IPL -Y to find floors,
// so the transformed scene MUST be Y-up at the IPL boundary. Distance fields
// crossing into IPL are scaled by kFeetToMeters.
namespace {

constexpr float kFeetToMeters = 0.3048f;
constexpr float kMetersToFeet = 1.0f / kFeetToMeters;

inline IPLVector3 engineToIplPos(const Vector3 &p) {
    return { -p.y * kFeetToMeters,
              p.z * kFeetToMeters,
             -p.x * kFeetToMeters };
}
inline Vector3 iplToEnginePos(const IPLVector3 &p) {
    return Vector3(-p.z * kMetersToFeet,
                   -p.x * kMetersToFeet,
                    p.y * kMetersToFeet);
}

} // namespace

// ── Ctor / dtor ───────────────────────────────────────────────────────────

ProbeManager::ProbeManager(ProbeManagerDeps deps)
    : mDeps(std::move(deps))
{
}

ProbeManager::~ProbeManager()
{
    // Release the probe batch if still loaded. We do not have a simulator
    // handle here (AudioService releases the simulator first in
    // destroyAcousticScene and then releases the manager), so this is a
    // pure release without simulator de-registration.
    if (mIplProbeBatch) {
        iplProbeBatchRelease(&mIplProbeBatch);
        mIplProbeBatch = nullptr;
        mProbeCount = 0;
    }
}

// ── Bake ──────────────────────────────────────────────────────────────────

bool ProbeManager::bakeProbes(IPLScene scene,
                              const std::string &outputPath,
                              const ProbeBakeParams &params,
                              std::atomic<float> *progress)
{
    if (!mDeps.context || !scene) {
        LOG_ERROR("ProbeManager: cannot bake probes — no acoustic scene");
        return false;
    }

    // Negative sentinel → use the manager's configured spacing/height.
    // Callers who want an explicit one-off bake spacing can pass a positive
    // value via ProbeBakeParams.
    float spacing = (params.spacingFtOverride > 0.0f) ? params.spacingFtOverride : mProbeSpacingFt;
    float height  = (params.heightFtOverride  > 0.0f) ? params.heightFtOverride  : mProbeHeightFt;

    AUDIO_LOG( "Baking probes: spacing=%.1f height=%.1f ...\n", spacing, height);

    // Step 1: Generate probes on a uniform floor grid
    IPLProbeArray probeArray = nullptr;
    IPLerror err = iplProbeArrayCreate(mDeps.context, &probeArray);
    if (err != IPL_STATUS_SUCCESS) {
        LOG_ERROR("ProbeManager: iplProbeArrayCreate failed (%d)", err);
        return false;
    }

    // Build the OBB transform for IPL_PROBEGENERATIONTYPE_UNIFORMFLOOR. Per
    // the Steam Audio docs, the transform maps an axis-aligned UNIT CUBE
    // [0,1]³ into world space. Probes are then generated by raycasting along
    // IPL -Y (its "down") to find floor surfaces, offset by `height` along
    // IPL +Y.
    //
    // Two non-obvious things to get right:
    //   1. The unit cube is [0,1]³ — NOT [-0.5, 0.5]³.  Using `center` as
    //      the translation would silently shift the entire probe volume by
    //      `extent/2` (symptoms: probes outside the playable area, above
    //      the player, behind walls in the +shift direction).
    //   2. IPL is Y-up while the engine is Z-up.  The mesh, listener, and
    //      sources are all in IPL Y-up space at this point (engineToIplPos
    //      at the boundary), so the probe OBB must be defined in IPL space
    //      too — otherwise UNIFORMFLOOR raycasts along the wrong axis and
    //      places probes wherever it happens to hit a wall.
    //
    // Mapping: an engine AABB at [(minX,minY,minZ), (maxX,maxY,maxZ)] in
    // feet maps to IPL [(minX, minZ, -maxY), (maxX, maxZ, -minY)] in meters.
    // We expand by one spacing on every side so probes cover near-edge
    // areas, then express the result as a [0,1]³ scale + translation.
    const Vector3 marginFt(spacing);
    Vector3 origMin = params.sceneMin - marginFt;       // engine-space, feet
    Vector3 origMax = params.sceneMax + marginFt;
    IPLVector3 iplCornerA = engineToIplPos(origMin);    // one IPL-space corner
    IPLVector3 iplCornerB = engineToIplPos(origMax);    // the opposite one
    IPLVector3 iplMin{ std::min(iplCornerA.x, iplCornerB.x),
                       std::min(iplCornerA.y, iplCornerB.y),
                       std::min(iplCornerA.z, iplCornerB.z) };
    IPLVector3 iplMax{ std::max(iplCornerA.x, iplCornerB.x),
                       std::max(iplCornerA.y, iplCornerB.y),
                       std::max(iplCornerA.z, iplCornerB.z) };

    IPLMatrix4x4 transform{};
    transform.elements[0][0] = iplMax.x - iplMin.x;  // IPL X scale (m)
    transform.elements[1][1] = iplMax.y - iplMin.y;  // IPL Y scale (m) — engine Z extent
    transform.elements[2][2] = iplMax.z - iplMin.z;  // IPL Z scale (m) — engine Y extent
    transform.elements[3][0] = iplMin.x;             // IPL X translation
    transform.elements[3][1] = iplMin.y;             // IPL Y translation
    transform.elements[3][2] = iplMin.z;             // IPL Z translation
    transform.elements[3][3] = 1.0f;

    AUDIO_LOG( "Scene bounds engine-ft: (%.0f,%.0f,%.0f)-(%.0f,%.0f,%.0f)\n"
               "Probe OBB engine-ft:     (%.0f,%.0f,%.0f)-(%.0f,%.0f,%.0f)\n"
               "Probe OBB IPL-m:         (%.2f,%.2f,%.2f)-(%.2f,%.2f,%.2f)\n",
                 params.sceneMin.x, params.sceneMin.y, params.sceneMin.z,
                 params.sceneMax.x, params.sceneMax.y, params.sceneMax.z,
                 origMin.x, origMin.y, origMin.z,
                 origMax.x, origMax.y, origMax.z,
                 iplMin.x, iplMin.y, iplMin.z,
                 iplMax.x, iplMax.y, iplMax.z);

    IPLProbeGenerationParams genParams{};
    genParams.type = IPL_PROBEGENERATIONTYPE_UNIFORMFLOOR;
    // spacing/height are passed in feet; IPL grid is in meters.
    genParams.spacing = spacing * kFeetToMeters;
    genParams.height  = height  * kFeetToMeters;
    genParams.transform = transform;

    iplProbeArrayGenerateProbes(probeArray, scene, &genParams);

    int numProbes = iplProbeArrayGetNumProbes(probeArray);
    AUDIO_LOG( "Generated %d probes (spacing=%.1f, height=%.1f)\n",
                 numProbes, spacing, height);

    if (numProbes == 0) {
        LOG_ERROR("ProbeManager: no probes generated — check scene geometry");
        iplProbeArrayRelease(&probeArray);
        return false;
    }

    // Step 2: Create probe batch and add the generated probes
    IPLProbeBatch probeBatch = nullptr;
    err = iplProbeBatchCreate(mDeps.context, &probeBatch);
    if (err != IPL_STATUS_SUCCESS) {
        LOG_ERROR("ProbeManager: iplProbeBatchCreate failed (%d)", err);
        iplProbeArrayRelease(&probeArray);
        return false;
    }

    // Snapshot probe centers BEFORE releasing the probeArray. We mirror them
    // into engine feet (Z-up) so the renderer's debug overlay doesn't need
    // to know anything about IPL's coordinate system.  iplToEnginePos
    // reverses both the metric scale AND the Y-up→Z-up axis swap that we
    // applied at the boundary above.
    mProbePositions.clear();
    mProbePositions.reserve(static_cast<size_t>(numProbes));
    for (int i = 0; i < numProbes; ++i) {
        IPLSphere s = iplProbeArrayGetProbe(probeArray, i);
        mProbePositions.push_back(iplToEnginePos(s.center));
    }

    iplProbeBatchAddProbeArray(probeBatch, probeArray);
    iplProbeArrayRelease(&probeArray);  // batch now owns the probe data

    // ── Extra coverage: elevation tier + portal-centric rings ──
    //
    // Pathing greedy-routes through the nearest visible probes. With
    // floor-only probes:
    //   - Elevated emitters (wall torches, ceiling lamps) snap to the
    //     floor probe under them — pathing reports their position as
    //     ground-level, distorting eqCoeffs near vertical edges.
    //   - Portal openings can be densely surrounded by floor probes
    //     that sit on either side of the wall but none in the doorway
    //     itself — pathing wraps around through adjacent grid probes
    //     and stretches chains.
    //
    // Both tiers are extra `iplProbeBatchAddProbe` calls with the same
    // sphere radius as floor probes (one `spacing` worth, in meters).
    // Steam Audio uses these in the visibility graph alongside the
    // floor probes — no special treatment needed at bake or runtime.

    // Mirror count for sidecar / debug overlay alignment.
    int extraProbeCount = 0;

    if (!params.additionalElevations.empty()) {
        const float probeRadiusM = spacing * kFeetToMeters;
        const size_t floorProbeCount = mProbePositions.size();
        for (float elevFt : params.additionalElevations) {
            if (elevFt <= 0.0f) continue;
            for (size_t i = 0; i < floorProbeCount; ++i) {
                Vector3 elevated = mProbePositions[i];
                elevated.z += elevFt;
                IPLSphere s{};
                s.center = engineToIplPos(elevated);
                s.radius = probeRadiusM;
                iplProbeBatchAddProbe(probeBatch, s);
                mProbePositions.push_back(elevated);
                ++extraProbeCount;
            }
        }
        AUDIO_LOG("Added %d elevation-tier probes "
                  "(floor count=%zu, tiers=%zu)\n",
                  extraProbeCount, floorProbeCount,
                  params.additionalElevations.size());
    }

    if (!params.portalAxes.empty()) {
        // Replace the legacy 4-probe on-portal-plane ring with up to 2
        // axial-offset probes per portal. Each candidate is dropped if
        // an existing floor/elevation probe already sits within
        // `dedupRadiusFt` — the floor grid covers it and a portal-anchor
        // there would only contribute duplicate IR weight at runtime.
        // Surviving candidates are the "openings without nearby grid
        // coverage" case (windows, vents, isolated hatches).
        const float probeRadiusM   = spacing * kFeetToMeters;
        const float axialOffsetFt  = params.portalAxialOffsetFt;
        const float dedupRadiusFt  = params.portalDedupRadiusFt;
        const float dedupRadiusSq  = dedupRadiusFt * dedupRadiusFt;

        // Snapshot the floor+elevation tier size BEFORE adding portal
        // probes so the proximity test only considers grid neighbours,
        // not the portal anchors we add inside the loop (otherwise the
        // second candidate of a portal pair would dedup against the
        // first, which is exactly the doorway hotspot we're fixing).
        const size_t gridProbeCount = mProbePositions.size();

        int portalProbeCount = 0;
        int dedupedCount     = 0;
        for (const auto &axis : params.portalAxes) {
            const Vector3 candidates[2] = {
                axis.center + axis.normal * axialOffsetFt,
                axis.center - axis.normal * axialOffsetFt,
            };
            for (const Vector3 &p : candidates) {
                // O(grid) brute scan — at miss6 sizes (~10k grid × ~1k
                // candidates) this is ~10M float ops, well under a
                // second. If bake density ever grows to where this
                // matters, swap to a uniform-cell hash on (x,y) — but
                // until then the simpler code is the better trade.
                bool tooClose = false;
                for (size_t i = 0; i < gridProbeCount; ++i) {
                    Vector3 d = mProbePositions[i] - p;
                    if (glm::dot(d, d) < dedupRadiusSq) { tooClose = true; break; }
                }
                if (tooClose) { ++dedupedCount; continue; }

                IPLSphere s{};
                s.center = engineToIplPos(p);
                s.radius = probeRadiusM;
                iplProbeBatchAddProbe(probeBatch, s);
                mProbePositions.push_back(p);
                ++extraProbeCount;
                ++portalProbeCount;
            }
        }
        AUDIO_LOG("Added %d portal-axis probes around %zu portals "
                  "(axialOffset=%.1fft, dedupRadius=%.1fft, "
                  "%d candidates deduped against floor grid)\n",
                  portalProbeCount, params.portalAxes.size(),
                  axialOffsetFt, dedupRadiusFt, dedupedCount);
    }

    if (extraProbeCount > 0) {
        // Keep numProbes in sync with the actual batch size so downstream
        // bake stages, the round-trip validation, and the .energy.csv
        // audit all iterate the full set.
        numProbes = static_cast<int>(mProbePositions.size());
        AUDIO_LOG("Total probes after extension: %d "
                  "(floor=%d, extra=%d)\n",
                  numProbes, numProbes - extraProbeCount, extraProbeCount);
    }

    iplProbeBatchCommit(probeBatch);

    // Step 3: Bake pathing data (visibility graph + shortest paths)
    AUDIO_LOG( "Baking pathing data for %d probes...\n", numProbes);

    IPLBakedDataIdentifier pathId{};
    pathId.type = IPL_BAKEDDATATYPE_PATHING;
    pathId.variation = IPL_BAKEDDATAVARIATION_DYNAMIC;

    // Pathing bake — all distance-shaped fields cross into IPL, so feet → meters.
    // `spacing` and `propagationMaxDist` live in engine feet; convert here.
    IPLPathBakeParams bakeParams{};
    bakeParams.scene = scene;
    bakeParams.probeBatch = probeBatch;
    bakeParams.identifier = pathId;
    bakeParams.numSamples = 4;                                          // visibility test samples (rays = numSamples²)
    bakeParams.radius = spacing * kFeetToMeters;                        // probe influence radius (m)
    bakeParams.threshold = 0.1f;                                        // visibility threshold (dimensionless)
    bakeParams.visRange  = params.propagationMaxDist * kFeetToMeters;   // max visibility distance (m)
    bakeParams.pathRange = params.propagationMaxDist * kFeetToMeters;   // max path length (m)
    bakeParams.numThreads = 4;                                          // parallel baking

    auto bakeStart = std::chrono::steady_clock::now();

    iplPathBakerBake(mDeps.context, &bakeParams,
        [](IPLfloat32 p, void *userData) {
            auto *prog = static_cast<std::atomic<float> *>(userData);
            if (prog) prog->store(p, std::memory_order_relaxed);
        },
        progress);

    auto bakeEnd = std::chrono::steady_clock::now();
    float bakeSec = std::chrono::duration<float>(bakeEnd - bakeStart).count();
    AUDIO_LOG( "Pathing bake complete: %d probes in %.1f seconds\n",
                 numProbes, bakeSec);

    // Step 3b: Bake reflection IRs at each probe position.
    // This pre-computes reverb impulse responses so that voices outside the
    // real-time top-N can use baked reverb instead of being dry.
    // Uses REVERB variation — one bake covers all sources (listener-position-based).
    AUDIO_LOG( "Baking reflection IRs for %d probes (rays=%d bounces=%d duration=%.1fs diffuse=%d order=%d)...\n",
                 numProbes, params.bakeNumRays, params.bakeNumBounces,
                 params.bakeDuration, params.bakeDiffuseSamples,
                 params.ambisonicsOrder);

    IPLBakedDataIdentifier reflId{};
    reflId.type = IPL_BAKEDDATATYPE_REFLECTIONS;
    reflId.variation = IPL_BAKEDDATAVARIATION_REVERB;

    unsigned int hwThreads = std::thread::hardware_concurrency();
    int bakeThreads = (params.simulatorThreads > 0)
        ? params.simulatorThreads
        : std::max(2u, hwThreads > 2 ? hwThreads - 2 : 2u);

    IPLReflectionsBakeParams reflBakeParams{};
    reflBakeParams.scene = scene;
    reflBakeParams.probeBatch = probeBatch;
    reflBakeParams.sceneType = (params.sceneType == "embree")
        ? IPL_SCENETYPE_EMBREE : IPL_SCENETYPE_DEFAULT;
    reflBakeParams.identifier = reflId;
    reflBakeParams.bakeFlags = static_cast<IPLReflectionsBakeFlags>(
        IPL_REFLECTIONSBAKEFLAGS_BAKECONVOLUTION);
    reflBakeParams.numRays = params.bakeNumRays;
    reflBakeParams.numDiffuseSamples = params.bakeDiffuseSamples;
    reflBakeParams.numBounces = params.bakeNumBounces;
    reflBakeParams.simulatedDuration = params.bakeDuration;
    reflBakeParams.savedDuration = params.bakeDuration;  // save full IR
    reflBakeParams.order = params.ambisonicsOrder;
    reflBakeParams.numThreads = bakeThreads;
    // irradianceMinDistance is in METERS (Steam Audio convention) — clamps the
    // inner radius of the irradiance integral to avoid singularities for sources
    // very close to a probe. 1.0m ≈ 3.28 ft is a sensible physical default.
    reflBakeParams.irradianceMinDistance = 1.0f;

    auto reflBakeStart = std::chrono::steady_clock::now();

    iplReflectionsBakerBake(mDeps.context, &reflBakeParams,
        [](IPLfloat32 p, void *userData) {
            auto *prog = static_cast<std::atomic<float> *>(userData);
            if (prog) prog->store(p, std::memory_order_relaxed);
        },
        progress);

    auto reflBakeEnd = std::chrono::steady_clock::now();
    float reflBakeSec = std::chrono::duration<float>(reflBakeEnd - reflBakeStart).count();
    AUDIO_LOG( "Reflection bake complete: %d probes in %.1f seconds\n",
                 numProbes, reflBakeSec);

    // Step 3c: Per-probe IR energy audit.
    //
    // Baked IRs vary wildly in total energy across probes. Probes sitting in
    // small enclosed spaces with hard surfaces accumulate disproportionate
    // diffuse-field energy compared to probes in open or absorbent areas.
    // When the listener's nearest probe is one of these "hot" IRs and a
    // continuous source (ambient) feeds the convolver, the wet bus saturates.
    //
    // This audit dumps per-probe metrics so we can identify outliers and
    // decide whether the fix belongs in bake parameters (absorption, bounces),
    // in probe rejection (skip outliers), or in IR normalization.
    //
    // The Steam Audio energy field is a 3D histogram of size
    // (#channels × #bands × #bins), with each bin being 10 ms of arrival time.
    // We compute:
    //   - totalEnergy: integrated energy across all channels/bands/bins
    //     (broadband, omnidirectional reverb intensity)
    //   - peakBin:     largest single-bin value (early-reflection clustering)
    //   - earlyEnergy: integrated energy in the first 50 ms (5 bins) — high
    //                  values mean clustered close-wall reflections
    //   - bandEnergy[3]: per-band totals — to spot frequency-specific spikes
    //                    (hard walls reflect highs; absorbent surfaces don't)
    //
    // Output is a `.energy.csv` sidecar next to the .probes file, plus a
    // stderr summary noting min/max/median total energy so outliers are
    // visible without grepping the CSV.
    {
        IPLEnergyFieldSettings efSettings{};
        efSettings.duration = params.bakeDuration;
        efSettings.order    = params.ambisonicsOrder;
        IPLEnergyField energyField = nullptr;
        IPLerror efErr = iplEnergyFieldCreate(mDeps.context, &efSettings,
                                              &energyField);
        if (efErr != IPL_STATUS_SUCCESS || !energyField) {
            LOG_INFO("ProbeManager: skipping IR energy audit — "
                     "iplEnergyFieldCreate returned %d", efErr);
        } else {
            int numChannels = iplEnergyFieldGetNumChannels(energyField);
            int numBins     = iplEnergyFieldGetNumBins(energyField);
            int numBands    = IPL_NUM_BANDS;

            std::string energyPath = outputPath + ".energy.csv";
            FILE *ef = std::fopen(energyPath.c_str(), "w");
            if (ef) {
                std::fprintf(ef, "# Per-probe IR energy metrics — written by "
                                 "ProbeManager::bakeProbes.\n"
                                 "# duration=%.2fs order=%d channels=%d "
                                 "bands=%d bins=%d (10ms per bin)\n",
                             params.bakeDuration, params.ambisonicsOrder,
                             numChannels, numBands, numBins);
                std::fprintf(ef, "index,x,y,z,totalEnergy,peakBin,"
                                 "earlyEnergy50ms,bandLow,bandMid,bandHigh\n");
            }

            std::vector<float> totals(numProbes, 0.0f);
            int earlyBins = std::min(5, numBins);  // first 50 ms

            for (int p = 0; p < numProbes; ++p) {
                iplEnergyFieldReset(energyField);
                iplProbeBatchGetEnergyField(probeBatch, &reflId, p,
                                             energyField);

                // Only the W channel (channel 0) is the omnidirectional
                // energy term and is guaranteed non-negative. Higher-order
                // Ambisonic channels are signed spherical-harmonic
                // coefficients that encode directional variation; summing
                // them produces meaningless near-zero/negative totals
                // because the harmonics cancel. The W coefficient is
                // proportional to the angular integral of incident energy,
                // which is exactly the per-probe "total reverb energy"
                // metric we want.
                double totalEnergy = 0.0;
                double earlyEnergy = 0.0;
                float  peakBin     = 0.0f;
                double bandEnergy[IPL_NUM_BANDS] = {0.0, 0.0, 0.0};

                for (int b = 0; b < numBands; ++b) {
                    const float *bins = iplEnergyFieldGetBand(
                        energyField, /*channel=*/0, b);
                    if (!bins) continue;
                    for (int t = 0; t < numBins; ++t) {
                        float v = bins[t];
                        totalEnergy   += v;
                        bandEnergy[b] += v;
                        if (t < earlyBins) earlyEnergy += v;
                        if (v > peakBin) peakBin = v;
                    }
                }
                totals[p] = static_cast<float>(totalEnergy);

                if (ef && p < static_cast<int>(mProbePositions.size())) {
                    const auto &pos = mProbePositions[p];
                    std::fprintf(ef,
                        "%d,%.3f,%.3f,%.3f,%.6e,%.6e,%.6e,%.6e,%.6e,%.6e\n",
                        p, pos.x, pos.y, pos.z,
                        totalEnergy, peakBin, earlyEnergy,
                        bandEnergy[0], bandEnergy[1], bandEnergy[2]);
                }
            }

            if (ef) {
                std::fclose(ef);
                AUDIO_LOG("Wrote probe IR energy sidecar '%s' (%d rows)\n",
                          energyPath.c_str(), numProbes);
            }

            // Stderr summary: min/median/max + indices so the outliers
            // jump out without inspecting the CSV. Probes whose totalEnergy
            // sits >10× above the median are the suspects for runaway
            // reverb when the listener parks near them.
            if (numProbes > 0) {
                std::vector<int> sorted(numProbes);
                for (int i = 0; i < numProbes; ++i) sorted[i] = i;
                std::sort(sorted.begin(), sorted.end(),
                          [&](int a, int b){ return totals[a] < totals[b]; });
                int minIdx = sorted.front();
                int maxIdx = sorted.back();
                int medIdx = sorted[numProbes / 2];
                float minE = totals[minIdx];
                float medE = totals[medIdx];
                float maxE = totals[maxIdx];
                int hotCount = 0;
                float hotThreshold = medE * 10.0f;
                for (float t : totals)
                    if (t > hotThreshold) ++hotCount;
                AUDIO_LOG("[PROBE_ENERGY] min=%.3e (probe %d) "
                          "median=%.3e (probe %d) max=%.3e (probe %d) "
                          "hot(>10×median)=%d/%d\n",
                          minE, minIdx, medE, medIdx, maxE, maxIdx,
                          hotCount, numProbes);
            }

            iplEnergyFieldRelease(&energyField);
        }
    }

    // Step 4: Serialize to memory buffer
    IPLSerializedObjectSettings soSettings{};
    soSettings.data = nullptr;
    soSettings.size = 0;

    IPLSerializedObject serializedObject = nullptr;
    err = iplSerializedObjectCreate(mDeps.context, &soSettings, &serializedObject);
    if (err != IPL_STATUS_SUCCESS) {
        LOG_ERROR("ProbeManager: iplSerializedObjectCreate failed (%d)", err);
        iplProbeBatchRelease(&probeBatch);
        return false;
    }

    iplProbeBatchSave(probeBatch, serializedObject);

    IPLsize dataSize = iplSerializedObjectGetSize(serializedObject);
    IPLbyte *data = iplSerializedObjectGetData(serializedObject);

    // Step 5: Round-trip validation — deserialize in memory and verify probe count
    // matches what we baked. Catches serialization bugs before they hit disk.
    {
        IPLSerializedObjectSettings rtSettings{};
        rtSettings.data = data;
        rtSettings.size = dataSize;
        IPLSerializedObject rtObj = nullptr;
        IPLProbeBatch rtBatch = nullptr;
        err = iplSerializedObjectCreate(mDeps.context, &rtSettings, &rtObj);
        if (err != IPL_STATUS_SUCCESS) {
            LOG_ERROR("ProbeManager: round-trip validation failed — "
                      "iplSerializedObjectCreate returned %d", err);
            iplSerializedObjectRelease(&serializedObject);
            iplProbeBatchRelease(&probeBatch);
            return false;
        }
        err = iplProbeBatchLoad(mDeps.context, rtObj, &rtBatch);
        iplSerializedObjectRelease(&rtObj);
        if (err != IPL_STATUS_SUCCESS) {
            LOG_ERROR("ProbeManager: round-trip validation failed — "
                      "iplProbeBatchLoad returned %d", err);
            iplSerializedObjectRelease(&serializedObject);
            iplProbeBatchRelease(&probeBatch);
            return false;
        }
        int rtCount = iplProbeBatchGetNumProbes(rtBatch);
        iplProbeBatchRelease(&rtBatch);
        if (rtCount != numProbes) {
            LOG_ERROR("ProbeManager: round-trip validation failed — "
                      "expected %d probes, deserialized %d", numProbes, rtCount);
            iplSerializedObjectRelease(&serializedObject);
            iplProbeBatchRelease(&probeBatch);
            return false;
        }
        AUDIO_LOG( "Round-trip validation passed (%d probes)\n", rtCount);
    }

    // Step 6: Write to disk with integrity header (atomic tmp+rename)
    bool writeOk = writeProbeFile(
        outputPath,
        reinterpret_cast<const uint8_t *>(data),
        static_cast<size_t>(dataSize),
        static_cast<uint32_t>(numProbes));

    iplSerializedObjectRelease(&serializedObject);
    iplProbeBatchRelease(&probeBatch);

    if (!writeOk) {
        LOG_ERROR("ProbeManager: failed to write probe file '%s'", outputPath.c_str());
        return false;
    }

    AUDIO_LOG( "Saved %d probes to '%s' (%zu bytes + %zu header)\n",
                 numProbes, outputPath.c_str(), static_cast<size_t>(dataSize),
                 kProbeFileHeaderSize);

    // Sidecar: dump probe positions as a plain CSV for the debug overlay.
    // The Steam Audio public API does NOT expose per-probe positions on a
    // deserialized IPLProbeBatch, so we mirror them ourselves. Plain text
    // keeps the file inspectable; cost is ~25 bytes/probe so even 50k probes
    // fits in ~1.2 MB. Failure to write is non-fatal — the overlay just
    // won't have positions until the next bake.
    {
        std::string posPath = outputPath + ".positions.csv";
        FILE *pf = std::fopen(posPath.c_str(), "w");
        if (pf) {
            std::fprintf(pf, "# Probe positions in engine feet — written by "
                              "ProbeManager::bakeProbes. spacing=%.2f height=%.2f\n",
                          spacing, height);
            std::fprintf(pf, "index,x,y,z\n");
            for (size_t i = 0; i < mProbePositions.size(); ++i) {
                const auto &p = mProbePositions[i];
                std::fprintf(pf, "%zu,%.3f,%.3f,%.3f\n", i, p.x, p.y, p.z);
            }
            std::fclose(pf);
            AUDIO_LOG("Wrote probe positions sidecar '%s' (%zu rows)\n",
                      posPath.c_str(), mProbePositions.size());
        } else {
            LOG_INFO("ProbeManager: could not write probe positions sidecar '%s' "
                     "(debug overlay will be empty until next bake)",
                     posPath.c_str());
        }
    }
    return true;
}

// ── Load ──────────────────────────────────────────────────────────────────

bool ProbeManager::loadProbes(const std::string &probePath,
                              IPLSimulator reflectionSimulator)
{
    if (!mDeps.context || !reflectionSimulator) {
        LOG_ERROR("ProbeManager: cannot load probes — no context/simulator");
        return false;
    }

    // Release any previously loaded probes
    if (mIplProbeBatch) {
        if (mDeps.waitForReflectionThread) mDeps.waitForReflectionThread();
        iplSimulatorRemoveProbeBatch(reflectionSimulator, mIplProbeBatch);
        iplSimulatorCommit(reflectionSimulator);
        iplProbeBatchRelease(&mIplProbeBatch);
        mIplProbeBatch = nullptr;
        mProbeCount = 0;
    }
    // Drop stale positions; we'll repopulate from the sidecar (or leave empty
    // if missing — overlay simply won't show anything in that case).
    mProbePositions.clear();
    mProbesHaveReflections = false;

    // Load and validate the probe file (header + CRC check)
    ProbeFileHeader hdr;
    std::vector<uint8_t> payload;
    ProbeFileStatus status = loadProbeFile(probePath, hdr, payload);

    if (status == ProbeFileStatus::FileNotFound) {
        LOG_INFO("ProbeManager: no probe file at '%s' — pathing disabled",
                 probePath.c_str());
        return false;
    }

    if (status != ProbeFileStatus::Ok) {
        LOG_ERROR("ProbeManager: probe file '%s' failed validation: %s — "
                  "delete and re-bake",
                  probePath.c_str(), probeFileStatusString(status));
        return false;
    }

    // Deserialize the validated payload
    IPLSerializedObjectSettings soSettings{};
    soSettings.data = reinterpret_cast<IPLbyte *>(payload.data());
    soSettings.size = static_cast<IPLsize>(payload.size());

    IPLSerializedObject serializedObject = nullptr;
    IPLerror err = iplSerializedObjectCreate(mDeps.context, &soSettings, &serializedObject);
    if (err != IPL_STATUS_SUCCESS) {
        LOG_ERROR("ProbeManager: iplSerializedObjectCreate failed (%d) loading '%s'",
                  err, probePath.c_str());
        return false;
    }

    err = iplProbeBatchLoad(mDeps.context, serializedObject, &mIplProbeBatch);
    iplSerializedObjectRelease(&serializedObject);

    if (err != IPL_STATUS_SUCCESS) {
        LOG_ERROR("ProbeManager: iplProbeBatchLoad failed (%d) for '%s'",
                  err, probePath.c_str());
        return false;
    }

    iplProbeBatchCommit(mIplProbeBatch);
    mProbeCount = iplProbeBatchGetNumProbes(mIplProbeBatch);

    // Cross-check: probe count from header must match what Steam Audio loaded
    if (mProbeCount != static_cast<int>(hdr.probeCount)) {
        LOG_ERROR("ProbeManager: probe count mismatch — header says %u, "
                  "Steam Audio loaded %d — discarding",
                  hdr.probeCount, mProbeCount);
        iplProbeBatchRelease(&mIplProbeBatch);
        mIplProbeBatch = nullptr;
        mProbeCount = 0;
        return false;
    }

    // Register with simulator
    if (mDeps.waitForReflectionThread) mDeps.waitForReflectionThread();
    iplSimulatorAddProbeBatch(reflectionSimulator, mIplProbeBatch);
    iplSimulatorCommit(reflectionSimulator);

    // Check if the probe batch contains baked reflection IRs.
    // If so, non-top-N voices can use baked reverb instead of being dry.
    IPLBakedDataIdentifier reflId{};
    reflId.type = IPL_BAKEDDATATYPE_REFLECTIONS;
    reflId.variation = IPL_BAKEDDATAVARIATION_REVERB;
    IPLsize reflDataSize = iplProbeBatchGetDataSize(mIplProbeBatch, &reflId);
    mProbesHaveReflections = (reflDataSize > 0);

    AUDIO_LOG( "ProbeManager: loaded %d probes from '%s' "
                 "(reflections=%s, refl_size=%zu bytes, crc=0x%08x)\n",
                 mProbeCount, probePath.c_str(),
                 mProbesHaveReflections ? "yes" : "no",
                 static_cast<size_t>(reflDataSize), hdr.crc32);

    // Load the positions sidecar (written by bakeProbes alongside the .probes
    // file). The Steam Audio public API doesn't expose per-probe positions on
    // a deserialized batch, so we keep our own mirror. If the sidecar is
    // missing or stale (count mismatch), debug overlays will simply be empty
    // until the next bake.
    std::string posPath = probePath + ".positions.csv";
    FILE *pf = std::fopen(posPath.c_str(), "r");
    if (pf) {
        char line[256];
        std::vector<Vector3> loaded;
        loaded.reserve(static_cast<size_t>(mProbeCount));
        while (std::fgets(line, sizeof(line), pf)) {
            if (line[0] == '#' || line[0] == 'i') continue;  // comment or header row
            int idx = 0;
            float x = 0.0f, y = 0.0f, z = 0.0f;
            if (std::sscanf(line, "%d,%f,%f,%f", &idx, &x, &y, &z) == 4) {
                loaded.emplace_back(x, y, z);
            }
        }
        std::fclose(pf);
        if (static_cast<int>(loaded.size()) == mProbeCount) {
            mProbePositions = std::move(loaded);
            AUDIO_LOG("ProbeManager: loaded %zu probe positions from sidecar '%s'\n",
                      mProbePositions.size(), posPath.c_str());
        } else {
            LOG_INFO("ProbeManager: probe positions sidecar count mismatch "
                     "(%zu in sidecar vs %d in batch) — overlay disabled until re-bake",
                     loaded.size(), mProbeCount);
        }
    } else {
        LOG_INFO("ProbeManager: no probe positions sidecar at '%s' — "
                 "overlay disabled until re-bake (existing probe data is fine)",
                 posPath.c_str());
    }
    return true;
}

// ── Release ───────────────────────────────────────────────────────────────

void ProbeManager::releaseBatch(IPLSimulator reflectionSimulator)
{
    if (!mIplProbeBatch) return;

    if (mDeps.waitForReflectionThread) mDeps.waitForReflectionThread();

    if (reflectionSimulator) {
        iplSimulatorRemoveProbeBatch(reflectionSimulator, mIplProbeBatch);
    }
    iplProbeBatchRelease(&mIplProbeBatch);
    mIplProbeBatch = nullptr;
    mProbeCount = 0;
    mProbesHaveReflections = false;
    mProbePositions.clear();
}

// ── Mission-relative probe file path ──────────────────────────────────────

std::string ProbeManager::getProbeFilePath(const std::string &misPath,
                                            const std::string &gameName)
{
    // Extract mission filename without extension
    std::string missionName;
    auto lastSlash = misPath.find_last_of("/\\");
    std::string filename = (lastSlash != std::string::npos)
        ? misPath.substr(lastSlash + 1) : misPath;
    auto dotPos = filename.rfind('.');
    missionName = (dotPos != std::string::npos)
        ? filename.substr(0, dotPos) : filename;

    // Convert to lowercase for consistency
    for (auto &c : missionName) c = static_cast<char>(std::tolower(c));

    // Build path: ~/darkness/{gameName}/baked_probes/{missionName}.probes
    const char *home = std::getenv("HOME");
    if (!home) home = ".";
    std::string dir = std::string(home) + "/darkness/" + gameName + "/baked_probes";

    // Create directories (mkdir -p equivalent)
    std::string pathSoFar;
    for (size_t i = 0; i < dir.size(); ++i) {
        if (dir[i] == '/' || i == dir.size() - 1) {
            pathSoFar = dir.substr(0, i + 1);
#ifdef _WIN32
            _mkdir(pathSoFar.c_str());
#else
            mkdir(pathSoFar.c_str(), 0755);
#endif
        }
    }

    return dir + "/" + missionName + ".probes";
}

} // namespace Darkness
