// GENERATED FILE — do not edit.
// Regenerate with:
//   python3 tools/gen_config_help.py darknessRender.example.yaml \
//       src/main/ConfigHelpText.h
//
// The YAML config reference printed by `darknessRender --help`, derived from
// darknessRender.example.yaml so the two cannot disagree. The example file is
// the authored source: every key, its default, and the reasoning behind it.
//
// Emitted as an array of lines rather than one string literal because MSVC
// caps a single string literal at 65535 bytes and this reference is close
// enough to that to be worth not thinking about again.
//
// tests/test_config_help.cpp fails if this file is stale relative to the
// example yaml, naming the missing keys.

#pragma once

namespace Darkness {

inline const char *const kConfigHelpLines[] = {
    "  paths:",
    "    res: \"\"                               Thief 2 RES directory (fam.crf, obj.crf, snd.crf).",
    "    schemas: \"\"                           Schema directory (.sch / .spc / .arc).",
    "",
    "  graphics:",
    "    texture_filter: point                 Texture filter mode (default: point)",
    "    lightmap_filter: bilinear             Lightmap filter mode (default: bilinear)",
    "    linear_mips: false                    Gamma-correct mipmap generation (default: false)",
    "    sharp_mips: false                     Sharpen mip levels to preserve detail at distance…",
    "    tweq_visibility_gating: true          Honour the tweq update-rate visibility gates (default:…",
    "    render_scale:                         Internal render resolution / vintage mode",
    "      height: 0                           Internal render HEIGHT in pixels; width follows the…",
    "      filter: point                       point  — chunky uniform pixels; what makes the vintage…",
    "      integer: true                       Snap the internal size so the upscale is a whole-number…",
    "    antialiasing:",
    "      mode: none                          none | smaa",
    "      smaa_threshold: 0.1                 Edge-detection threshold. Lower finds more edges: more…",
    "    sky_glow:                             Sky glow / sky overbright",
    "      enabled: true                       Sun/moon glow disc from the mission's SKYOBJVAR glow_*…",
    "      intensity: 1.0                      Multiplies the mission's authored glow_scale (default:…",
    "      sky_overbright: 1.0                 Sky brightness multiplier (default: 1.0 = untouched).",
    "    coronas:                              Light coronas",
    "      enabled: true                       Master switch, both sources. (default: true)",
    "      synthesized: true                   The enhancement, on its own switch. Set false for…",
    "      intensity: 1.0                      Multiplies each corona's authored alpha. Past ~1 the…",
    "      size_scale: 1.0                     Multiplies both corona radii. (default: 1.0)",
    "      max_distance_scale: 1.0             Multiplies each corona's own max visible distance.…",
    "      fade_seconds: 0.15                  Occlusion crossfade time constant, seconds. 0 snaps,…",
    "      depth_fade: true                    Per-pixel depth fade: attenuate a corona where scene…",
    "      depth_fade_range: 1.5               How far in front of a corona an occluder must be to hide…",
    "      depth_fade_offset: 0.5              Pull the billboard this far toward the viewer before…",
    "      trace_objects: true                 Occlude coronas by objects — doors, crates, characters —…",
    "      trace_samples: 5                    Rays per visibility test. 1 = centre only, so a corona…",
    "      trace_budget: 32                    Coronas re-traced per frame; the rest hold their…",
    "    post_process:                         Post-processing",
    "      enabled: false                      Master toggle (default: false — original-fidelity output)",
    "      tonemap: none                       Tone-mapping operator (default: none)",
    "      agx_contrast: 1.25                  [agx] Curve contrast (0.6-2.0, default 1.25 = Godot's).",
    "      lottes_contrast: 1.30               0.6-3.0",
    "      lottes_shoulder: 0.977              0.7-1.0; LOWER = longer, softer highlight rolloff",
    "      lottes_white: 3.0                   Scene value that maps to display white; everything above…",
    "      exposure: 1.0                       Linear multiplier applied before tone mapping (0.0-8.0,…",
    "      brightness: 0.0                     additive offset (-1.0-1.0, default: 0.0)",
    "      contrast: 1.0                       about the 0.5 pivot (0.0-4.0, default: 1.0)",
    "      saturation: 1.0                     0 = greyscale (0.0-4.0, default: 1.0)",
    "      gamma: 1.0                          applied last (0.1-4.0, default: 1.0)",
    "      rgb_filter: [1.0, 1.0, 1.0]         RGB colour filter [r, g, b], each 0.0-1.0 (default: [1,…",
    "      luma_mode: crt                      Luminance weighting - \"what counts as bright\". Drives…",
    "      bloom:                              Bloom. Construction follows HPL2 (Amnesia: The Dark…",
    "        enabled: false                    (default: false)",
    "        style: amnesia                    Which engine's bloom construction: amnesia | newdark…",
    "        iterations: 2                     [both] H+V passes, 1-4 (HPL2 ships 2). Radius",
    "        blur_size: 1.0                    [both] blur radius multiplier (HPL2 ships 1.0 =",
    "        intensity: 1.0                    [amnesia] scales the luminance vector (HPL2 ships 1.0)",
    "        threshold: 0.6                    min channel value to be included in bloom (0-1)",
    "        prescale: 1.0                     intensity multiplier applied BEFORE blurring",
    "        scale: 5.0                        intensity multiplier applied AFTER blurring",
    "        saturation: 0.7                   saturation of the glow itself (0 = greyscale)",
    "        range: 0.0                        [both] Glow radius as a percentage of the screen…",
    "      film:                               Film response",
    "        strength: 0.0                     0.0-1.0. Start low; 0.3-0.5 is a shroud, 1.0 is a…",
    "        shadow_saturation: 0.55           Saturation kept at each end (0.0-2.0). The shadow figure…",
    "        highlight_saturation: 1.0",
    "        shadow_tint: [1.0, 1.0, 1.0]      Multiplicative split tone, [r, g, b], each 0.0-1.0.…",
    "        highlight_tint: [1.0, 0.98, 0.94] Highlights warm, because the light sources in this game…",
    "        tone_falloff: 1.5                 How tightly each tint is confined to its own end of the…",
    "      halation:                           Halation (the CineStill effect)",
    "        strength: 0.0                     0.0-4.0",
    "        tint: [1.0, 0.32, 0.12]           red-orange, each 0.0-1.0",
    "        threshold: 1.0                    0.0-4.0",
    "        radius: 10.0                      1.0-16.0",
    "      grain:",
    "        strength: 0.0                     0.0-0.5; 0.02-0.06 is a light dusting",
    "        size: 1.5                         0.25-8.0 output pixels per noise cell; >1 clumps",
    "",
    "  water:",
    "    wave_amplitude: 0.3                   Vertex wave displacement amplitude in world units…",
    "    uv_distortion: 0.015                  UV texture distortion strength (default: 0.015)",
    "    rotation_speed: 0.015                 UV rotation speed in radians/sec (default: 0.015)",
    "    scroll_speed: 0.05                    UV scroll speed in world units/sec (default: 0.05)",
    "",
    "  physics:",
    "    rate: 60                              Physics timestep rate (default: 60)",
    "",
    "  developer:",
    "    show_objects: true                    Render object meshes (default: true)",
    "    show_fallback_cubes: false            Show colored fallback cubes for objects with missing…",
    "    portal_culling: true                  Portal/frustum culling (default: true)",
    "    camera_collision: false               Camera collision with world geometry (default: false)",
    "    step_log: false                       Log stair step diagnostics to stderr (default: false)",
    "    debug_objects: false                  Dump per-object filtering diagnostics to stderr…",
    "    toggle_platforms: false               Auto-activate all moving terrain at startup (default:…",
    "    no_probes: false                      Skip Steam Audio probe baking (default: false)",
    "    audio_log: false                      Enable audio/sound/schema log output (default: false)",
    "    capture_wav: false                    Record the engine's final stereo output (f32 WAV, post…",
    "",
    "  audio:",
    "    engine:",
    "      ring_mixer: true                    Device-callback / mixer-thread topology (immutable after…",
    "      ring_margin_ms: -1                  Ring fill target in milliseconds. The mixer thread tops…",
    "    performance:",
    "      sample_rate: 48000                  [GLOBAL] device sample rate…",
    "      frame_size: 512                     [GLOBAL] audio engine block size (256–4096); callback…",
    "      sound_cache_mb: 64                  [GLOBAL] decoded-audio LRU cache budget (4–1024 MB)",
    "      max_active_voices: 64               [GLOBAL] hard cap on simultaneous voices (8–256)",
    "      reverb_voices: 8                    (0–64)",
    "      reverb_voices_realtime: 0           [REALTIME] Of the reverb voices above, how many may run…",
    "      rate_divisor: 2                     [REFLECTIONS] 1=48k, 2=24k, 4=12k",
    "      reflection_throttle: 4              [REFLECTIONS] (1–32)",
    "      sim_max_occlusion_samples: 32       [DIRECT+REFLECTIONS] (4–256)",
    "      conv_threads: 0                     thread budget",
    "      sim_threads: 0",
    "      scene_type: default                 [REFLECTIONS]",
    "    reflections:",
    "      enabled: true                       [REFLECTIONS] master toggle (R key in console)",
    "      ambisonics_order: 0                 0–3",
    "      hybrid_transition_time: 1.0         seconds; pure conv 0..(T*(1-O))s, blend T*(1-O)..T s",
    "      hybrid_overlap_percent: 0.25        fraction of transition_time used for crossfade",
    "      realtime:                           Realtime simulation params (running every…",
    "        rays: 2048                        rays per realtime sim step (128–8192)",
    "        bounces: 4                        bounces per ray (1–8); biggest CPU lever (each +1…",
    "        duration: 1.1                     IR duration in seconds (must exceed…",
    "        diffuse_samples: 32               diffuse scattering samples per bounce (16–256)",
    "      bake:                               Offline bake params (run once per mission; cached as…",
    "        rays: 16384                       rays per bake step (1024–65536)",
    "        bounces: 16                       bake bounces (1–64)",
    "        duration: 1.1                     bake IR duration in seconds (>= realtime.duration; only…",
    "        diffuse_samples: 1024             bake diffuse samples (32–4096)",
    "        ambisonics_order: 2               bake ambisonic order (0–3); may be higher than runtime…",
    "    probes:",
    "      spacing: 5.0                        grid spacing in feet (1.0–20.0; re-bake required)",
    "      height: 5.0                         probe height above floor in feet (0.5–20.0)",
    "      elevations: [10.0]                  Extra elevations (feet, above each floor probe) to…",
    "      min_wall_clearance_ft: 5.0          (0–50; 0 = clearance check off)",
    "      elevation_sparsity_mul: 2.0         (1.0–8.0; higher = sparser; re-bake required)",
    "      global_dedup_radius_ft: 2.0         (0.0–10.0; re-bake required)",
    "    pathing_probes:",
    "      enabled: true                       Steam Audio pathing uses a separate, sparse probe batch",
    "      dedup_radius_ft: 10.0               (0.0–30.0)",
    "      vis_range_override_ft: 0.0          (0.0–400.0; 0 = coverage-derived)",
    "      density: bends                      (baseline | bends; re-bake on change)",
    "    occlusion:",
    "      radius: 10.0                        volumetric source sphere (feet, 0.3–30)",
    "      samples: 16                         rays per source for occlusion gradient (4–64)",
    "      transmission_scale: 1.0             material transmission multiplier (0.1–100;…",
    "      absorption_scale: 0.75              material absorption multiplier (0.01–10; <1 = more…",
    "    propagation:",
    "      portal_routing: true                route sound through portal graph (doorways)",
    "      probe_pathing: true                 baked probe diffraction (when probes loaded)",
    "      max_distance: 200.0                 max propagation distance (world units, 10–5000)",
    "      door_lpf_open_hz: 20000             LPF cutoff for fully open door (Hz, 1k–24k)",
    "      door_lpf_blocked_hz: 800            LPF cutoff for fully blocked door (Hz, 100–10k)",
    "      min_attenuation: 0.0                propagation floor (0–0.1; floor disabled by default; was…",
    "      max_paths: 2                        simultaneous propagation paths per listener (1–4)",
    "      max_path_diff: 50.0                 alternate-path distance window (world units, 0–50)",
    "      pathing_gain_scale: 1.0             multiplier on pathing gain (0.1–10.0)",
    "      pathing_blocking_scale: 1.0         Multiplier on the pathing-derived LPF blocking factor —…",
    "      pathing_update_interval: 0.05       min seconds between pathing due ticks (0.0–1.0);…",
    "      pathing_router_gate: true           Router-gated search: when the door-aware route graph…",
    "      pathing_noroute_move_mul: 4         No-route movement damping: a voice whose last Steam…",
    "      pathing_smoothing_ms: 100           smoothing time constant for pathing EQ/SH between…",
    "      pathing_gain_band_weights: [0.25, 0.50, 0.25] Per-band weights for collapsing Steam Audio's…",
    "    spatialization:",
    "      hrtf_volume: 1.0                    HRTF output gain (0–4)",
    "      hrtf_interpolation: bilinear        \"nearest\" or \"bilinear\" (HRTF dataset interpolation)",
    "      spatial_blend: 1.0                  0=mono center, 1=full HRTF spatialization",
    "    ambient:",
    "      spawn_fade_in_ms: 150               volume ramp 0→full on voice spawn (0–2000 ms)",
    "      halt_fade_out_ms: 250               volume ramp full→0 before halt-stop (0–2000 ms)",
    "      halt_audibility_threshold_db: -50   dB level below which voice is \"inaudible\" (-80 to -20)",
    "      halt_below_threshold_frames: 30     consecutive sub-threshold frames before halt (5–600)",
    "      default_priority: 64                priority for ambients without explicit value (0–255)",
    "      environmental_spatial_blend: 0.3    (0.0–1.0)",
    "      global_volume_scale: 1.0            (0.0–4.0)",
    "    mixer:",
    "      master_gain: 1.0                    global output multiplier (0–4)",
    "      direct_gain: 0.5                    dry-bus multiplier — direct path only (0–4)",
    "      reflection_gain: 0.5                reverb wet bus multiplier — indirect path (0–4)",
    "      reflection_ramp_ms: 10.0            fade-in time on first reflection activation (1–1000 ms)",
    "    dsp:",
    "      limiter_enabled: true               soft tanh limiter (prevents digital clipping)",
    "      limiter_knee: 0.8                   onset threshold (0.5–0.95)",
    "      compressor_enabled: true            tames transients",
    "      compressor_threshold_db: -12.0      dBFS threshold (-30 to 0)",
    "      compressor_ratio: 5.0               compression ratio (1.5–10)",
    "      compressor_attack_ms: 10.0          attack time (1–100 ms)",
    "      compressor_release_ms: 250.0        release time (50–2000 ms)",
    "      eq_enabled: true                    low-shelf EQ (adds bass weight)",
    "      eq_freq_hz: 120.0                   center frequency (60–500 Hz)",
    "      eq_gain_db: 3.0                     shelf gain (-6 to +6 dB)",
    "      eq_q: 0.707                         filter Q (0.3–2.0; 0.707 = Butterworth)",
    "      ducking_enabled: false              duck ambients when SFX plays",
    "      ducking_amount: 0.5                 ambient volume during ducking (0.1–1.0)",
    "      ducking_attack_ms: 50.0             ducking attack (10–500 ms)",
    "      ducking_release_ms: 500.0           ducking release (50–5000 ms)",
    "      wet_saturation_enabled: false       apply tanh saturation to wet bus",
    "      wet_saturation_drive: 1.0           saturation drive (1.0–10.0)",
};

inline constexpr int kConfigHelpLineCount =
    static_cast<int>(sizeof(kConfigHelpLines) / sizeof(kConfigHelpLines[0]));

} // namespace Darkness
